# Generated by Django 3.0.3 on 2020-02-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone_Piloter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, default='', max_length=50)),
                ('mdt', models.DateTimeField(auto_now=True)),
                ('exp', models.BooleanField(default='')),
                ('drone', models.BooleanField(default='')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('birth', models.DateField()),
                ('email', models.CharField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('addr', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='event_happening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, default='', max_length=50)),
                ('mdt', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=50)),
                ('message_type', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, default='', max_length=50)),
                ('mdt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('crop', models.CharField(blank=True, default='', max_length=50)),
                ('area', models.IntegerField(blank=True)),
                ('birth', models.DateField()),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('addr', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer_Order_completed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, default='', max_length=50)),
                ('mdt', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(blank=True, default='', max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('addr', models.CharField(blank=True, default='', max_length=255)),
                ('mission_date', models.DateField(blank=True, default='')),
                ('mission_crop', models.CharField(blank=True, default='', max_length=50)),
                ('mission_area', models.IntegerField(blank=True)),
                ('mission_item', models.CharField(blank=True, default='', max_length=50)),
                ('mission_addr', models.CharField(blank=True, default='', max_length=255)),
                ('mission_latitude', models.FloatField(blank=True)),
                ('mission_longitude', models.FloatField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer_Order_Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, default='', max_length=50)),
                ('mdt', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(max_length=50)),
                ('mission_date', models.DateField()),
                ('mission_crop', models.CharField(blank=True, default='', max_length=50)),
                ('mission_area', models.IntegerField(blank=True)),
                ('mission_item', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='postback_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, default='', max_length=50)),
                ('mdt', models.DateTimeField(auto_now=True)),
                ('mPostBack', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='user_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(blank=True, default='', max_length=50)),
                ('p_picture', models.CharField(blank=True, default='', max_length=200)),
                ('souce_type', models.CharField(blank=True, max_length=10)),
                ('gid', models.CharField(blank=True, default='', max_length=50)),
                ('uid', models.CharField(max_length=50)),
                ('mid', models.CharField(max_length=50)),
                ('mtext', models.CharField(max_length=500)),
                ('rtk', models.CharField(max_length=50)),
                ('mdt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
